# headplane-secret-splice
#
# A NixOS module that runs Headplane (the web UI for Headscale) while solving
# three problems the plain "render a config file" approach cannot:
#
#   1. Secrets must never land in the Nix store. A YAML file generated by Nix is
#      world-readable in /nix/store, so the cookie secret, OIDC client secret and
#      Headscale API key are spliced into /etc/headplane/config.yaml by a root
#      oneshot with `yq` at boot instead of being written by Nix.
#   2. Headplane hardcodes /etc/headplane and /var/lib/headplane. Those are not
#      configurable, so the module writes to them directly.
#   3. Headplane reads a *copy* of Headscale's config, not the live file, and
#      won't notice upstream changes. A sync oneshot copies the (rebuild-varying)
#      store config to a stable path, and a path unit restarts Headplane whenever
#      that file or extra_records.json changes.
#
# Secret file paths are module options -- point them at whatever secrets manager
# you use (agenix, sops-nix, a systemd credential, a plain root-only file).
{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib)
    mkEnableOption
    mkIf
    mkOption
    mkPackageOption
    types
    ;
  cfg = config.services.headplane;

  # Hardcoded by upstream headplane; not configurable in the app.
  headplaneConfigHardcodedPath = "/etc/headplane";
  headplaneStateHardcodedPath = "/var/lib/headplane";

  # Stable path we copy headscale's rebuild-varying store config into so the
  # path-watch unit has something durable to observe.
  headscaleStablePath = "/var/lib/headscale";

  settingsFormat = pkgs.formats.yaml { };
  settingsFile = settingsFormat.generate "headplane-config.yaml" cfg.settings;
in
{
  # Replace the upstream nixpkgs module with this one.
  disabledModules = [ "services/networking/headplane.nix" ];

  options.services.headplane = {
    enable = mkEnableOption "headplane (Headscale web UI)";
    package = mkPackageOption pkgs "headplane" { };

    user = mkOption {
      type = types.str;
      default = config.services.headscale.user or "headscale";
      defaultText = lib.literalExpression "config.services.headscale.user";
      description = ''
        User headplane runs as. Defaults to the headscale user so headplane can
        read headscale's state directory.
      '';
    };

    group = mkOption {
      type = types.str;
      default = config.services.headscale.group or "headscale";
      defaultText = lib.literalExpression "config.services.headscale.group";
      description = "Group headplane runs as. Defaults to the headscale group.";
    };

    settings = mkOption {
      type = types.submodule {
        freeformType = settingsFormat.type;
      };
      default = { };
      description = ''
        Headplane config; rendered to YAML. Do NOT put secrets here -- they would
        end up world-readable in /nix/store. Put secret file paths in
        `secretFiles` instead; they are spliced into the rendered config at boot.
        See https://github.com/tale/headplane/blob/main/config.example.yaml
      '';
    };

    secretFiles = {
      cookieSecret = mkOption {
        type = types.nullOr types.path;
        default = null;
        example = "/run/agenix/headplane-cookie-secret";
        description = ''
          Path to a root-readable file containing headplane's session cookie
          secret. Spliced into `.server.cookie_secret` at boot. If null, the
          key is left as whatever `settings` provided.
        '';
      };

      oidcClientSecret = mkOption {
        type = types.nullOr types.path;
        default = null;
        example = "/run/agenix/headplane-oidc-secret";
        description = ''
          Path to a root-readable file containing the OIDC client secret.
          Spliced into `.oidc.client_secret` at boot.
        '';
      };

      headscaleApiKey = mkOption {
        type = types.nullOr types.path;
        default = null;
        example = "/run/agenix/headscale-api-key";
        description = ''
          Path to a root-readable file containing the Headscale API key.
          Spliced into `.headscale.api_key` at boot.
        '';
      };
    };
  };

  config = mkIf cfg.enable {
    # 1. Copy headscale's store-path config to a stable file so the path unit
    #    below has something durable to watch. headplane reads this copy.
    systemd.services.headplane-sync-headscale-config = {
      description = "Copy headscale config to stable path for headplane";
      wantedBy = [ "headplane.service" ];
      before = [ "headplane.service" ];
      after = [ "headscale.service" ];
      partOf = [ "headscale.service" ];
      script = ''
        mkdir -p ${headscaleStablePath}
        cp -f ${config.services.headscale.configFile} ${headscaleStablePath}/config.yaml
        chown ${cfg.user}:${cfg.group} ${headscaleStablePath}/config.yaml
        chmod 640 ${headscaleStablePath}/config.yaml
      '';
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        User = "root";
      };
    };

    # 2. Render the config, then splice secrets in with yq -- as root, so the
    #    secrets never touch the world-readable Nix store.
    systemd.services.headplane-config-generator = {
      description = "Generate headplane configuration with secrets";
      wantedBy = [ "headplane.service" ];
      before = [ "headplane.service" ];
      after = [
        "headscale.service"
        "headplane-sync-headscale-config.service"
      ];
      partOf = [ "headscale.service" ];
      path = [ pkgs.yq-go ];

      script = ''
        # Create both dirs with tight modes *before* any secret is written, so
        # config.yaml is never reachable through a world-readable parent -- not
        # even in the window between the copy/splice and the final chmod.
        install -d -m 0700 -o ${cfg.user} -g ${cfg.group} ${headplaneStateHardcodedPath}
        install -d -m 0750 -o ${cfg.user} -g ${cfg.group} ${headplaneConfigHardcodedPath}
        rm -f ${headplaneConfigHardcodedPath}/config.yaml
        # Install the secret-free base config with an explicit owner-only-plus-group
        # mode up front; the splices below preserve it (yq edits in place).
        install -m 0640 -o ${cfg.user} -g ${cfg.group} ${settingsFile} ${headplaneConfigHardcodedPath}/config.yaml

        ${lib.optionalString (cfg.secretFiles.cookieSecret != null) ''
          COOKIE_SECRET=$(cat ${cfg.secretFiles.cookieSecret})
          export COOKIE_SECRET
          yq eval -i '.server.cookie_secret = strenv(COOKIE_SECRET)' ${headplaneConfigHardcodedPath}/config.yaml
        ''}
        ${lib.optionalString (cfg.secretFiles.oidcClientSecret != null) ''
          CLIENT_SECRET=$(cat ${cfg.secretFiles.oidcClientSecret})
          export CLIENT_SECRET
          yq eval -i '.oidc.client_secret = strenv(CLIENT_SECRET)' ${headplaneConfigHardcodedPath}/config.yaml
        ''}
        ${lib.optionalString (cfg.secretFiles.headscaleApiKey != null) ''
          API_KEY=$(cat ${cfg.secretFiles.headscaleApiKey})
          export API_KEY
          yq eval -i '.headscale.api_key = strenv(API_KEY)' ${headplaneConfigHardcodedPath}/config.yaml
        ''}

        touch ${headplaneStateHardcodedPath}/users.json

        # Re-assert ownership/modes in case yq's in-place rewrite reset them.
        chown -R ${cfg.user}:${cfg.group} ${headplaneStateHardcodedPath} ${headplaneConfigHardcodedPath}
        chmod 750 ${headplaneConfigHardcodedPath}
        chmod 640 ${headplaneConfigHardcodedPath}/config.yaml
        chmod 700 ${headplaneStateHardcodedPath}
        chmod 600 ${headplaneStateHardcodedPath}/users.json
      '';

      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        User = "root";
      };
    };

    # 3. Watch the stable headscale state and restart headplane on change,
    #    since headplane reads a copy and won't reload on its own.
    systemd.paths.headplane-watch-headscale-state = {
      description = "Watch headscale state for changes";
      wantedBy = [ "multi-user.target" ];
      pathConfig = {
        PathChanged = [
          "${headscaleStablePath}/config.yaml"
          "${headscaleStablePath}/extra_records.json"
        ];
        Unit = "headplane-reload.service";
      };
    };

    systemd.services.headplane-reload = {
      description = "Reload headplane after headscale state change";
      script = ''
        /run/current-system/sw/bin/systemctl restart headplane.service
      '';
      serviceConfig = {
        Type = "oneshot";
        User = "root";
      };
    };

    environment.systemPackages = [ cfg.package ];

    systemd.services.headplane = {
      description = "Headscale Web UI";

      wantedBy = [ "multi-user.target" ];
      after = [
        "headscale.service"
        "headplane-sync-headscale-config.service"
        "headplane-config-generator.service"
      ];
      wants = [ "headscale.service" ];

      serviceConfig = {
        User = cfg.user;
        Group = cfg.group;

        ExecStart = "${cfg.package}/bin/headplane";
        Restart = "always";
        RestartSec = 5;

        NoNewPrivileges = true;
        PrivateTmp = true;
        PrivateDevices = true;

        ReadWritePaths = [
          headplaneConfigHardcodedPath
          headplaneStateHardcodedPath
          headscaleStablePath
        ];
      };
    };
  };
}
